### ISSUE TITLE
'Cannot read property 'toLowerCase' of undefined'

### ISSUE THREAD

**Issue by captainhook** [bitwarden/directory-connector#130] opened 2021-06-05 23:37 UTC
It seems as soon as I check the 'Sync users' or 'Sync groups' checkboxes, either with valid filters/paths or left blank, I get the following error when attempting to sync:

`An error has occured. Cannot read property 'toLowerCase' of undefined`

I cannot see anything in the console/network tab, and cannot find any logs to indicate what the issue may be.

User filter:
`(&(objectCategory=Person)(sAMAccountName=*)(memberOf=CN=Access_Bitwarden,OU=Access,OU=Groups,OU=Resources,DC=xxx,DC=xxx,DC=xxx))`

This was working absolutely fine about a week ago before I updated to 2.9.2, but I've tested with earlier versions and I'm getting the same error. Is there any way I can debug this further?

**Comment by eliykat** [comment] 2021-06-06 21:54
Hi @captainhook, can you please post a screenshot of the errors that appear in the DevTools console? (View > Toggle Developer Tools > Console)

**Comment by cscharf** [comment] 2021-06-07 15:09
Also, can you please add some additional detail around which directory provider you're syncing/connecting to (LDAP, G-suite, Okta, Azure, etc.)? I see a few places in the code this _could_ happen, but it really depends which provider/service is being invoked.

**Comment by captainhook** [comment] 2021-06-08 02:06
> 
> 
> Hi @captainhook, can you please post a screenshot of the errors that appear in the DevTools console? (View > Toggle Developer Tools > Console)

Hi eliykat,
The only thing in the console is:
`DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/admin/AppData/Local/Temp/1sPChGVHJKXmZuISlzOgv6UmJqm/resources/app.asar/app/share.js.map: Unexpected end of JSON input`

This is from when the connector launches. When I click 'test now', nothing new presents in the console even with verbose logging enabled.



> 
> 
> Also, can you please add some additional detail around which directory provider you're syncing/connecting to (LDAP, G-suite, Okta, Azure, etc.)? I see a few places in the code this _could_ happen, but it really depends which provider/service is being invoked.

Apologies - that would've been useful! I am using AD/LDAP

In settings I have the following:
![MKO7zZFGdb](https://user-images.githubusercontent.com/16797541/121111014-b4dd7e00-c7fd-11eb-8818-1b4268b645e2.png)

It's definitely connecting to AD just fine - I know this because without 'Sync users' checked, it doesn't throw a LdapErr message, and it successfully enumerates 0 users/groups to sync. Once either 'Sync users' or 'Sync groups' is selected, the error mentioned in the issue occurs.

**Comment by captainhook** [comment] 2021-06-08 02:36
I have entered a root path and relative 'User Path' and 'Group Path' - which I didn't have set in v2.8, instead I had absolute paths set in 'User Path' and 'Group Path' - and it's now working absolutely fine. Sorry, folks, I should've tried that sooner.

Happy to close this issue, or if you have any further questions then please do ask.

**Comment by eliykat** [comment] 2021-06-08 04:21
Good to hear you figured it out! To clarify, was this bug caused by you changing your settings (from absolute to relative paths), or were your settings the same and directory connector's behaviour changed?

Can you give me an example of your absolute vs. relative path? Which one worked?

Just want to make sure this isn't a broader issue, and maybe we can provide a better error message.

**Comment by eliykat** [comment] 2021-06-24 20:44
This doesn't appear to be a widespread issue and no further info has been provided - closing.

**Closed by eliykat** 2021-06-24 20:44 UTC
