### ISSUE TITLE
Sync fails silently when number of users exceeds available licenses

### ISSUE THREAD

**Issue by tobias--** [bitwarden/directory-connector#28] opened 2019-08-30 08:01 UTC
The sync apparently fails silently if the number of synced users is bigger than the number of available seats. The UI says X users where synced, when in fact not a single one was synced.

None of the log files indicated that a sync failed. Not on the local client (directory connector) and not in any of the logs on the server. The nginx access log indicates, that the request to /import was successful (200).

**Comment by kspearrin** [comment] 2019-08-30 13:44
Thanks. This has been a known issue. We can track it here now.

**Comment by gricey432** [comment] 2020-02-17 05:18
For us, the desire would be to be able to tell the CLI to buy more licenses if needed, not just to fail. But failing would also be better than the current result, just wasted a fair bit of time trying to figure out what I'd done wrong before seeing this issue. In the interim would you accept a PR to the docs noting this behaviour?

**Comment by kalumkalac** [comment] 2020-06-10 10:14
The problem is not only that it fails silenty, but also that the users who should have been synced are written in the cache as if they were really synced. Consequently, even if you add seats afterward, the users are still not synced. You have to force a clear-cache. If not fixed quickly, this info should at least be on the doc.

I reach out to the support as well for this issue.

**Comment by eliykat** [comment] 2021-07-15 07:27
Fixed by https://github.com/bitwarden/server/pull/1241.

**Closed by eliykat** 2021-07-15 07:27 UTC

**Comment by gricey432** [comment] 2021-07-16 01:17
Experience this improvement the other day and it was a big help. Thanks team!
