### ISSUE TITLE
Missing paged control

### ISSUE THREAD

**Issue by AdamVB** [bitwarden/directory-connector#40] opened 2020-04-29 12:10 UTC
This Issue is similar to the one that has already been closed: https://github.com/bitwarden/directory-connector/issues/16

Essentially we get the same error message. But the proposed solution (remove repeated pathing) didn't work out for us.

Here's our config:

```
{

  "directoryType": 0,
  "directoryConfig_0": {
    "ssl": true,
    "sslAllowUnauthorized": true,
    "port": "636",
    "currentUser": false,
    "ad": false,
    "hostname": "ldap.otc-service.internal",
    "rootPath": "dc=otc,dc=app",
    "username": "cn=bind_username,ou=profile,dc=otc,dc=app",
        "sslCaPath": "xxxxxxxx.crt",
    "password": "xxxxxxx"
  },
  "directoryConfig_2": {},
  "directoryConfig_1": {},
  "directoryConfig_3": {},
  "syncConfig": {
    "users": true,
    "groups": false,
    "interval": 5,
    "removeDisabled": false,
    "overwriteExisting": false,
    "useEmailPrefixSuffix": false,
    "creationDateAttribute": "whenCreated",
    "revisionDateAttribute": "whenChanged",
    "emailPrefixAttribute": "sAMAccountName",
    "memberAttribute": "memberUid",
    "userObjectClass": "person",
    "groupObjectClass": "posixGroup",
    "userEmailAttribute": "mail",
    "groupNameAttribute": "cn",
    "userFilter": "",
    "groupFilter": "",
    "groupPath": "ou=group",
    "userPath": "ou=people"
  },
```
bind usernames are under ou=profile,,dc=otc,dc=app users are in ou=people,dc=otc,dc=app and groups in ou=group,dc=otc,dc=app

When doing the sync test it shows this error
```
./bwdc test
missing paged control
```

ldapsearch works fine with that bind user 

Any Ideas?

**Comment by kspearrin** [comment] 2020-05-13 13:01
@AdamVB Can you try debugging the LDAP quries that are generated?

> You can debug the LDAP queries from the output in the console under View > Developer Tools. Or, if using the CLI, you can set environment variable BWCLI_DEBUG=true to see the LDAP query debug output in terminal.

**Comment by kareemshayeb** [comment] 2020-05-13 17:08
@kspearrin using the CLI, the only message we get is this:

`missing paged control`

However, with the GUI tool we get this in the developer console:

`internal/process/warning.js:23 (node:32205) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

**Comment by kspearrin** [comment] 2020-05-13 21:03
@kareemshayeb I am having trouble reproducing the issue. Here is what I am using:

```
	"directoryConfig_0": {
		"ssl": true,
		"startTls": false,
		"sslAllowUnauthorized": true,
		"port": "636",
		"currentUser": false,
		"ad": false,
		"password": "Secret123",
		"hostname": "ipa.demo1.freeipa.org",
		"username": "uid=admin,cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org",
		"rootPath": "dc=demo1,dc=freeipa,dc=org"
	},
	"syncConfig": {
		"users": true,
		"groups": true,
		"interval": 5,
		"removeDisabled": true,
		"overwriteExisting": true,
		"useEmailPrefixSuffix": true,
		"creationDateAttribute": "whenCreated",
		"revisionDateAttribute": "whenChanged",
		"emailPrefixAttribute": "sAMAccountName",
		"memberAttribute": "member",
		"userObjectClass": "person",
		"groupObjectClass": "posixGroup",
		"userEmailAttribute": "mail",
		"groupNameAttribute": "cn",
		"groupPath": "ou=group",
		"userPath": "ou=people",
		"userFilter": "",
		"emailSuffix": "@company.com"
	},
```

**Comment by kareemshayeb** [comment] 2020-05-14 08:00
@kspearrin I've noticed from your configs two new options comparing to that what I'm using..
First is `"startTls": false,` which didn't make any difference.
Although, this one did `"emailSuffix": "@company.com"`. The moment I test the LDAP connection with this option, I get logged out and the content of "data.json" get wiped out.
Anyhow, the same issue still there!

> $ bwdc test
User search: ou=people,dc=otc,dc=app => (&(objectClass=person))
missing paged control

**Comment by kspearrin** [comment] 2020-05-14 14:49
@kareemshayeb I am using the latest dev build, which has some new unreleased options. Could you try the latest dev build from here and see if the issue persists?

https://ci.appveyor.com/project/bitwarden/directory-connector/builds/32756074/job/0bnbhinwvkvbmsbm/artifacts

**Comment by kareemshayeb** [comment] 2020-05-14 15:02
This didn't solve the issue, and the same error message still shows up.

**Comment by kspearrin** [comment] 2020-05-14 15:06
@kareemshayeb Are you able to give us access to your environment in some way? I don't know what else to do if I cannot reproduce the issue.

**Comment by kareemshayeb** [comment] 2020-05-14 15:10
@kspearrin  We can set up a Webex Meeting if you like.

**Comment by kspearrin** [comment] 2020-05-14 15:21
@kareemshayeb I could join a video call, but I would still probably need to be able to query the environment in some way to reproduce the problem while debugging.

**Comment by kareemshayeb** [comment] 2020-05-14 15:33
I can grant you access during the meeting, this would be the fastest way.
Otherwise, we need to figure out how to grant you access on our environment. This needs to be discussed then within our team.

**Comment by kspearrin** [comment] 2020-05-19 17:42
@kareemshayeb @AdamVB This is fixed in https://github.com/bitwarden/directory-connector/pull/45

You can now control from the client settings if your server supports paging or not.

This will be available next release. You can try the latest dev builds here:

- https://ci.appveyor.com/project/bitwarden/directory-connector/builds/32983159/job/cuhnnrdmu7poo0gr/artifacts
- https://ci.appveyor.com/project/bitwarden/directory-connector/builds/32983159/job/dotsslp27yhy0ndn/artifacts

**Closed by kspearrin** 2020-05-19 17:42 UTC
